### ISSUE TITLE
Что не работает

### ISSUE THREAD

**Issue by Svet55555** [RomanStudensky/restoran#11]
Состав списания -> Добавить -> ошибка при сохранении
Товарная накладная -> Удалить (не удаляется)
Товарная накладная -> Изменить (при изменении одной записи может меняться несколько)
Состав поставки -> Добавить -> ошибка при сохранении
Состав поставки -> Удалить (не удаляется)
Бронь -> Изменить -> ошибка при сохранении
Бронь -> Удалить (не удаляется)
Заказ -> Добавить (выбираешь одного сотрудника, добавляется другой)
Заказ -> Изменить -> ошибка при сохранении
Состав заказа -> Удалить (не удаляется)

**Comment by RomanStudensky** [comment]
Состав списания -> Добавить -> ошибка при сохранении
![изображение](https://user-images.githubusercontent.com/90255897/145802793-4ff4823f-56f1-4fc1-8907-7a91b7e9077f.png)
Такая ошибка вылазит?

**Comment by RomanStudensky** [comment]
Товарная накладная -> Удалить (не удаляется)
Сейчас попробовал - удаляется
в новой версии ещё потесть
