### ISSUE TITLE
Состав заказа (не удаляется)

### ISSUE THREAD

**Issue by Svet55555** [RomanStudensky/restoran#27]
![состав заказа (удалить)](https://user-images.githubusercontent.com/95649839/165965195-9231c97e-4878-4328-9d80-e458a11c9032.png)
можно еще при добавлении нового заказа в выпадающем списке Сотрудник сделать так чтобы там были только официанты?

**Comment by RomanStudensky** [comment]
Исправил удаление

**Comment by RomanStudensky** [comment]
> ![состав заказа (удалить)](https://user-images.githubusercontent.com/95649839/165965195-9231c97e-4878-4328-9d80-e458a11c9032.png) можно еще при добавлении нового заказа в выпадающем списке Сотрудник сделать так чтобы там были только официанты?

Сделал добавление только официантов
