### ISSUE TITLE
Выгрузка меню

### ISSUE THREAD

**Issue by Svet55555** [RomanStudensky/restoran#28]
![выгрузка меню (официант, бармен)](https://user-images.githubusercontent.com/95649839/165965560-b1e81bc2-ec4a-4ce3-b3c2-b85b22f7fca3.png)
можно выгрузку меню убрать у бухгалтера/директора, а сделать у официанта и бармена
и еще по поводу бухгалтера и директора, можно сделать, если заходит директор (user5), то написано Ресторан - Директор, а если бухгалтер (user8), то Ресторан - Бухгалтер

**Comment by RomanStudensky** [comment]
Выгрузку поправил
Остальное нельзя
